import pandas as pd
import numpy as np

# Paths to source CSV files
source0_path = 'autopipeline-benchmarks/github-pipelines/length4_80/test_0.csv'
source1_path = 'autopipeline-benchmarks/github-pipelines/length4_80/test_1.csv'

# Path to output CSV
output_path = 'autopipeline-benchmarks/github-pipelines/length4_80/target_multisource_cot.csv'

# Load source tables; ignore first column as index (index_col=0)
source0 = pd.read_csv(source0_path, index_col=0)
source1 = pd.read_csv(source1_path, index_col=0)

# The source0 columns: ['Mouse ID', 'Timepoint', 'Tumor Volume (mm3)', 'Metastatic Sites']
# The source1 columns: ['Mouse ID', 'Drug']

# Join on 'Mouse ID' to associate Drug with tumor volumes and metastatic sites
merged = pd.merge(source0, source1, on='Mouse ID', how='inner')

# Check for nan after merge, drop if any (guaranteed by inner join but safe)
merged = merged.dropna(subset=['Drug', 'Timepoint', 'Tumor Volume (mm3)', 'Metastatic Sites', 'Mouse ID'])

# Calculate aggregations: Mean and SEM of Tumor Volume (mm3) by ['Drug', 'Timepoint', 'Mouse ID', 'Metastatic Sites']

# SEM = standard deviation / sqrt(n)
agg_df = merged.groupby(['Drug', 'Timepoint', 'Mouse ID', 'Metastatic Sites'], as_index=False).agg({
    'Tumor Volume (mm3)': ['mean', 'std', 'count']
})

# Flatten MultiIndex columns generated by aggregation
agg_df.columns = ['Drug', 'Timepoint', 'Mouse ID', 'Metastatic Sites', 'Mean Tumor Volume', 'Std Tumor Volume', 'Count']

# Calculate SEM of Tumor Volume (mm3)
agg_df['SEM Tumor Volume'] = agg_df['Std Tumor Volume'] / np.sqrt(agg_df['Count'])

# Replace NaN SEM (when count=1 => std=NaN) with 0
agg_df['SEM Tumor Volume'] = agg_df['SEM Tumor Volume'].fillna(0)

# According to target schema:
# Rename columns according to target schema exact names:
# 'Mean of Tumor Volume (mm3)': float
# 'SEM of Tumor Volume (mm3)': integer (we round or floor)
# Also, convert 'Mouse ID' from string to integer by mapping unique IDs to integers (because target's Mouse ID is int)

# Map Mouse ID strings to integers consistently (starting from 1)
unique_mouse_ids = sorted(agg_df['Mouse ID'].unique())
mouse_id_map = {mid: idx+1 for idx, mid in enumerate(unique_mouse_ids)}
agg_df['Mouse ID'] = agg_df['Mouse ID'].map(mouse_id_map).astype(int)

# Convert metastasic sites to int (already int likely, but ensure)
agg_df['Metastatic Sites'] = agg_df['Metastatic Sites'].astype(int)

# Rename columns consistent with target schema
agg_df.rename(columns={
    'Mean Tumor Volume': 'Mean of Tumor Volume (mm3)',
    'SEM Tumor Volume': 'SEM of Tumor Volume (mm3)'
}, inplace=True)

# SEM column is integer in target, round and convert to int
agg_df['SEM of Tumor Volume (mm3)'] = agg_df['SEM of Tumor Volume (mm3)'].round().astype(int)

# Ensure 'Timepoint' is integer
agg_df['Timepoint'] = agg_df['Timepoint'].astype(int)

# Reorder columns according to target schema
final_df = agg_df[['Drug', 'Timepoint', 'Mean of Tumor Volume (mm3)', 'Mouse ID', 'SEM of Tumor Volume (mm3)', 'Metastatic Sites']]

# Save the transformed DataFrame to CSV
final_df.to_csv(output_path, index=False)