import pandas as pd

s0 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_0.csv", index_col=0)
s1 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_1.csv", index_col=0)
s2 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_2.csv", index_col=0)
s3 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_3.csv", index_col=0)
s4 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_4.csv", index_col=0)
s5 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_5.csv", index_col=0)
s6 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_6.csv", index_col=0)
s7 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_7.csv", index_col=0)
s8 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_8.csv", index_col=0)
s9 = pd.read_csv("autopipeline-benchmarks/github-pipelines/length9_20/training_9.csv", index_col=0)

df = pd.merge(s3, s0, how='left', left_on='Pronostico', right_on='Pronostico', suffixes=('', '_s0'))
df = pd.merge(df, s1, how='left', left_on='Deteccion', right_on='Deteccion', suffixes=('', '_s1'))
df = pd.merge(df, s2, how='left', left_on='Origen', right_on='Origen', suffixes=('', '_s2'))
df = pd.merge(df, s4, how='left', left_on='Intervencion', right_on='Intervencion', suffixes=('', '_s4'))
df = pd.merge(df, s5, how='left', left_on='Riesgo', right_on='Riesgo', suffixes=('', '_s5'))
df = pd.merge(df, s6, how='left', left_on='Actividad', right_on='Actividad', suffixes=('', '_s6'))
df = pd.merge(df, s7, how='left', left_on='Reanimacion', right_on='Reanimacion', suffixes=('', '_s7'))
df = pd.merge(df, s8, how='left', left_on='Causa', right_on='Causa', suffixes=('', '_s8'))
df = pd.merge(df, s9, how='left', left_on='Factor', right_on='Factor', suffixes=('', '_s9'))

result = pd.DataFrame()
result['Fecha'] = df['Fecha'].astype(str)
result['Mes'] = pd.to_numeric(df['Mes'], errors='coerce').astype('Int64')
result['IdAhogado'] = pd.to_numeric(df['IdAhogado'], errors='coerce').astype('Int64')
result['IdPersona'] = pd.to_numeric(df['IdPersona'], errors='coerce').astype('Int64')
result['Localidad'] = df['Localidad'].astype(str)
result['Provincia'] = df['Provincia'].astype(str)
result['CCAA'] = df['CCAA'].astype(str)
result['Hora'] = df['Hora'].astype(str)
result['Latitud_inc'] = pd.to_numeric(df['Latitud_inc'], errors='coerce')
result['Longitud_inc'] = pd.to_numeric(df['Longitud_inc'], errors='coerce')
result['Sexo'] = df['Sexo'].astype(str)
result['Edad'] = pd.to_numeric(df['Edad'], errors='coerce')
result['Nacionalidad'] = df['Nacionalidad'].astype(str)
result['Origen'] = df['Origen'].astype(str)
result['Extraccion'] = df['Extraccion'].astype(str)
result['Causa'] = df['Causa'].astype(str)
result['TipoAhogamiento'] = df['TipoAhogamiento'].astype(str)
result['Factor'] = df['Factor'].astype(str)
result['Intervencion'] = df['Intervencion'].astype(str)
result['Pronostico'] = df['Pronostico'].astype(str)
result['Localizacion'] = df['Localizacion'].astype(str)
result['Riesgo'] = df['Riesgo'].astype(str)
result['Reanimacion'] = df['Reanimacion'].astype(str)
result['Vigilancia'] = df['Vigilancia'].astype(str)
result['Actividad'] = df['Actividad'].astype(str)
result['Deteccion'] = df['Deteccion'].astype(str)
result['ID'] = pd.to_numeric(df['ID'], errors='coerce').astype('Int64')
result['Estacion'] = df['Estacion'].astype(str)
result['Estado'] = df['Estado'].astype(str)
result['Latitud_est'] = pd.to_numeric(df['Latitud_est'], errors='coerce')
result['Longitud_est'] = pd.to_numeric(df['Longitud_est'], errors='coerce')
result['T_med'] = pd.to_numeric(df['T_med'], errors='coerce')
result['T_max'] = pd.to_numeric(df['T_max'], errors='coerce')
result['T_min'] = pd.to_numeric(df['T_min'], errors='coerce')
result['Precipitaciones'] = pd.to_numeric(df['Precipitaciones'], errors='coerce')
result['Presion'] = pd.to_numeric(df['Presion'], errors='coerce')
result['Dir. vi.'] = pd.to_numeric(df['Dir. vi.'], errors='coerce')
result['V_Viento'] = pd.to_numeric(df['V_Viento'], errors='coerce').astype('Int64')
result['Nubosidad'] = pd.to_numeric(df['Nubosidad'], errors='coerce')
result['ProfNievecm'] = pd.to_numeric(df['ProfNievecm'], errors='coerce')
result['InsolacHoras'] = pd.to_numeric(df['InsolacHoras'], errors='coerce')
result['Distancia'] = pd.to_numeric(df['Distancia'], errors='coerce')
result['IdActividad'] = pd.to_numeric(df['IdActividad'], errors='coerce').astype('Int64')
result['IdCausa'] = pd.to_numeric(df['IdCausa'], errors='coerce').astype('Int64')
result['IdDeteccion'] = pd.to_numeric(df['IdDeteccion'], errors='coerce').astype('Int64')
result['IdFactor'] = pd.to_numeric(df['IdFactor'], errors='coerce').astype('Int64')
result['IdInterv'] = pd.to_numeric(df['IdInterv'], errors='coerce').astype('Int64')
result['IdOrigen'] = pd.to_numeric(df['IdOrigen'], errors='coerce').astype('Int64')
result['IdPronostico'] = pd.to_numeric(df['IdPronostico'], errors='coerce').astype('Int64')
result['Mortal'] = pd.to_numeric(df['Mortal'], errors='coerce').astype('Int64')
result['IdReanima'] = pd.to_numeric(df['IdReanima'], errors='coerce').astype('Int64')
result['IdRiesgo'] = pd.to_numeric(df['IdRiesgo'], errors='coerce').astype('Int64')

result.to_csv("autopipeline-benchmarks/github-pipelines/length9_20/target_multisource_mcts.csv", index=False)