# agentflow/tools/configure_join_operator/tool.py

import ast
import re
import sys
from pathlib import Path
from typing import Any, Dict, Optional

from agentflow.engine.factory import create_llm_engine
from agentflow.tools.base import BaseTool

_TRANSCHEMA_ROOT = str(Path(__file__).resolve().parents[5])
if _TRANSCHEMA_ROOT not in sys.path:
    sys.path.insert(0, _TRANSCHEMA_ROOT)
from hints.hints_static import get_hints_section, JOIN_HINT_IDS


# Tool name mapping - this defines the external name for this tool
TOOL_NAME = "Configure_Join_Operator_Tool"



def _extract_between_dollars(text: str) -> Optional[str]:
    if not text:
        return None
    m = re.search(r"\$(.*?)\$", text, flags=re.DOTALL)
    if not m:
        return None
    return m.group(1).strip()


def _safe_literal_eval_list(text: str) -> Optional[Any]:
    """Best-effort parse of a Python-like literal list."""
    if not text:
        return None
    try:
        return ast.literal_eval(text)
    except Exception:
        return None


def get_join_prompt(transformation_case_info: str) -> str:
    """Generate join prompt using the provided transformation case information."""
    prompt = f"""
You are generating a data-pipeline to transform multiple source tables to target table and you need to answer "what tables should be joined and at which columns?". Take this decision based on the transformation case information provided below.

{transformation_case_info}

- Please answer which tables should be joined and at which columns that hasn't appeared yet in "operation history".
{get_hints_section(JOIN_HINT_IDS, fmt="bullet")}
- You should only answer from available columns of the source tables.
- Only return two tables that should be joined and on which columns.
- You may use the tables that are generated by the previous actions. You may refer to them as join_result_0, join_result_1, etc. if needed.
- Choose tables that contain columns similar to columns in the target tables to be joined.
- The final answer should be in format of list.
- The first element of list should be the list of two tables that should be joined.
- The next elements should be list of two columns on which the join should be perfomed.
- i.e. [ [table1, table2], [table1.join_column1,table2.join_column1], [table1.join_column2,table2.join_column2],...]
- The final answer list should be within $ quotes strictly. [i.e. $ Final Answer List $]
    """
    return prompt


class Configure_Join_Operator_Tool(BaseTool):
    require_llm_engine = True

    def __init__(self, model_string: str = "gpt-4o-mini"):
        super().__init__(
            tool_name=TOOL_NAME,
            tool_description="A tool that configures a JOIN operator by selecting which two tables to join and the join columns.",
            tool_version="1.0.0",
            input_types={
                "query": "str - Transformation case information including Target Table Name, Target Schema, Target Examples, and Multi Source Information.",
            },
            output_type="dict - Contains the join configuration as a parsed list when possible, plus raw LLM response and prompt.",
            demo_commands=[
                {
                    "command": 'execution = tool.execute(query="1. Target Table Name: Target1_0\\n2. Target Schema: [State: string, AverageTemperature: float]\\n3. Target Examples: ...\\n4. Multi Source Information: ...")',
                    "description": "Configure a JOIN from transformation case information.",
                }
            ],
        )

        # NOTE: deterministic mode
        self.llm_engine = create_llm_engine(
            model_string=model_string,
            is_multimodal=False,
            temperature=0.0,
            top_p=1.0,
            frequency_penalty=0.0,
            presence_penalty=0.0,
        )

    def execute(self, query: str = "") -> Dict[str, Any]:
        """Execute the tool with the provided transformation case information."""
        if not query:
            raise ValueError(
                "query parameter is required and must contain transformation case information"
            )

        full_prompt = get_join_prompt(query)

        response = self.llm_engine(full_prompt)
        response_str = str(response)

        payload = _extract_between_dollars(response_str) or response_str.strip()
        join_list = _safe_literal_eval_list(payload)

        return {
            "join_spec": join_list if join_list is not None else payload,
            "raw_response": response_str,
            "prompt": full_prompt,
        }


if __name__ == "__main__":
    tool = Configure_Join_Operator_Tool(model_string="gpt-4o-mini")
    print(
        tool.execute(
            query="""
1. Target Table Name: Target1_0
2. Target Schema: ['State': string, 'AverageTemperature': float]
3. Target Examples: State AverageTemperature
Zhejiang 16.18
4. Multi Source Information:
Source 0 Name: Source1_0_0
Source 0 Schema: ['dt', 'AverageTemperature', 'AverageTemperatureUncertainty', 'State', 'Country']
5. Operation History: []
""".strip()
        )
    )
