"""
This module provides functions evaluation the quality of generated sql code.

The module contains a collection of functions that perform quality  checks on the generated SQL code.

There are two types of quality checks:
Type 1: Static analysis of the SQL code
Type 2: Dynamic analysis of the table generated by SQL code

Type 1 quality checks are performed by the following functions:
    sql_attribute_converage(sql_query, source_data_name_to_find, target_data_name, conn) :
        Returns the attribute coverage of the generated SQL code.
    sql_insert_mapping(sql_query, source_data_name_to_find, target_data_name, conn) :
        Returns the inter-table mapping of the generated SQL code.

Type 2 quality checks are performed by the following functions:
    table_statistics_check(sql_query, source_data_name_to_find, target_data_name, conn) :
        Returns the statistics of the table generated by the SQL code.
    reversibility_check(sql_query, source_data_name_to_find, target_data_name, conn) :
        Returns the reversibility of the generated SQL code.


"""
import re
import ast
from util.utils import execute_sql, compare_lists_matching
import sqlparse
from sqlparse.sql import Identifier, IdentifierList
from sqlparse.tokens import DML
import json
from decimal import Decimal
from util.FDTool.fdtool.modules import GetFDs, Apriori_Gen, binaryRepr
import csv
import pandas as pd
import os


def schema_quality(sql_query, **kwargs):
    source_columns, target_columns = extract_table_schemas(sql_query, kwargs['source_name'], kwargs['target_name'])
    # Clean up column names from the SQL query (removing quotes)
    target_columns_clean = [x.replace('"', '') for x in target_columns]
    source_columns_clean = [x.split(" ")[-1].replace('"', '') if " AS " in x else x for x in
                            source_columns]  # Extract alias if exists
    # Properly parse the schema strings
    source_data_schema_list = ast.literal_eval(kwargs['source_schema'][0])
    target_data_schema = ast.literal_eval(kwargs['target_schema'])

    matching_target_count = len([col for col in target_columns_clean if col in target_data_schema])
    matching_source_count = len([col for col in source_columns_clean if col in source_data_schema_list])
    mismatch_1 = [col for col in target_columns_clean if col not in target_data_schema]
    mismatch_2 = [col for col in source_columns_clean if col not in source_data_schema_list]

    if not mismatch_1 and not mismatch_2:
        mismatch_feedback = "Schema matches correctly."
    else:
        mismatch_feedback = ""
        if mismatch_1:
            mismatch_feedback += "\n Mismatch in target column: " + str(mismatch_1)
        if mismatch_2:
            mismatch_feedback += "\n Mismatch in Source column: " + str(mismatch_2)
    # Calculate the individual scores
    score_3_2 = matching_target_count / len(target_data_schema) if len(target_data_schema) != 0 else 0

    # Calculate the individual scores
    score_3_1 = matching_source_count / len(source_data_schema_list) if len(source_data_schema_list) != 0 else 0
    quality_score = (score_3_1 + score_3_2) / 2
    column_mappings, target_handle = perform_column_mapping_analysis(sql_query, target_columns_clean,
                                                                     source_columns_clean)
    missing_target_attributes = [col for col in target_data_schema if col not in target_handle]
    mismatch_feedback += "\n Missing handle target attributes: " + str(missing_target_attributes)
    # Penalize the quality score based on missing attributes
    missing_attribute_penalty = len(missing_target_attributes) / len(target_data_schema) if kwargs[
        'target_schema'] else 0
    quality_score *= (1 - missing_attribute_penalty)
    return quality_score, mismatch_feedback, column_mappings, target_handle


def perform_column_mapping_analysis(gpt_output, target_columns_clean, source_columns_clean):
    # Parse the SQL query
    parsed_statements = sqlparse.parse(gpt_output)
    column_mappings = []
    target_handle = []
    # Split the script into individual statements
    statements = [stmt for stmt in sqlparse.split(gpt_output) if stmt.strip()]

    # Find the last 'INSERT INTO' statement
    last_insert_statement = None
    for statement in reversed(statements):
        if "INSERT INTO" in statement.upper():
            last_insert_statement = statement
            break

    # Extract the column names from the last 'INSERT INTO' statement
    if last_insert_statement:
        match = re.search(r'INSERT INTO\s+"?\w+"?\s+\((.*?)\)', last_insert_statement, re.IGNORECASE)
        if match:
            columns = match.group(1).split(',')
            target_handle = [col.strip().strip('"').strip("'") for col in columns]

    for statement in parsed_statements:
        if statement.get_type() == "INSERT":
            for token in statement.tokens:
                if token.ttype is DML and token.value.upper() == "SELECT":
                    select_part = token.parent
                    identifiers = [item for item in select_part.tokens if isinstance(item, IdentifierList)]
                    if identifiers:
                        identifier_list = identifiers[0].get_identifiers()
                        for idx, identifier in enumerate(identifier_list):
                            if idx < len(target_columns_clean):  # Check if idx is within the range
                                target_col = target_columns_clean[idx]
                                extracted_columns = extract_source_column_from_token(identifier, source_columns_clean)
                                for col in extracted_columns:
                                    column_mappings.append((col, target_col))
                            else:
                                print(f"Index {idx} is out of range for target columns.")
    seen = set()
    unique_mappings = []
    for mapping in column_mappings:
        if mapping not in seen:
            seen.add(mapping)
            unique_mappings.append(mapping)
    # Further logic could be added here to handle more complex duplicate scenarios.

    return unique_mappings, target_handle


def extract_source_column_from_token(token, source_columns_clean):
    extracted_columns = []
    if isinstance(token, Identifier) and token.get_real_name() in source_columns_clean:
        extracted_columns.append(token.get_real_name())
    elif hasattr(token, 'tokens'):
        for subtoken in token.tokens:
            extracted_columns.extend(extract_source_column_from_token(subtoken, source_columns_clean))
    return extracted_columns


def extract_table_schemas(sql_query, source_data_name_to_find, target_data_name):
    source_schema = {}
    target_schema = {}

    # Remove lines that are comments
    sql_query = '\n'.join([line for line in sql_query.split('\n') if not line.strip().startswith('--')]).strip()

    # Split SQL queries based on semicolon and filter out empty strings
    queries = [q.strip() for q in sql_query.split(";") if q.strip()]

    # Improved regex pattern to match column names and types correctly
    # Including those with type definitions containing parentheses
    column_pattern = r'(?:(`[^`]+`)|"([^"]+)"|(\[\^,\]+)|(\w+))\s+([\w()]+(?:\(\d+(?:,\d+)?\))?)'

    for query in queries:
        # Match CREATE TABLE statements more accurately
        match = re.match(r"CREATE TABLE \"?(\w+)\"? \((.*)\)", query, re.IGNORECASE | re.DOTALL)
        if match:
            table_name, columns_str = match.groups()
            # Adjusted to use the improved regex for column matching
            columns_list = re.findall(column_pattern, columns_str)

            # Process matched columns to build the schema dictionary
            column_schema = {col[1] or col[2] or col[3]: col[4].upper() for col in columns_list if col}

            # Assign to source or target schema based on the table name
            if table_name == source_data_name_to_find:
                source_schema = column_schema
            elif table_name == target_data_name:
                target_schema = column_schema

    return source_schema, target_schema


def data_quality(sql_result, conn, agent, gpt_output):
    score_1 = calculate_data_quality_score(sql_result)
    if score_1 < 0.6:
        print("Data quality low")
        agg_prompt = "Some hints for the schema changes from the first table to the second table:Consider using aggregation functions."
        ini_prompt = agent.prompt
        agent.prompt = agent.prompt + agg_prompt
        # Second Iteration: Execute modified prompt
        gpt_output_modified = agent.run_baseline()
        sql_result_modified = execute_sql(conn, gpt_output_modified)
        dq_score_modified = calculate_data_quality_score(sql_result_modified)
        agent.prompt = ini_prompt
        print(f"New SQL Query: {gpt_output_modified}")
        print(f"New Table: {sql_result_modified}")
        print(f"Modified Data Quality Score: {dq_score_modified}")

        # Compare the scores
        if dq_score_modified > score_1:
            print("Data quality improved with aggregation.")
            sql_result = sql_result_modified
            gpt_output = gpt_output_modified
            dq_score = dq_score_modified
            return dq_score, gpt_output, sql_result
        else:
            print("No significant improvement in data quality.")
            return score_1, gpt_output, sql_result
    else:
        return score_1, gpt_output, sql_result


def calculate_data_quality_score(sql_result):
    if not sql_result or not sql_result[0]:
        return 0  # No data to evaluate

    num_cols = len(sql_result[0])
    num_rows = len(sql_result)

    # Initialize counters and holders
    none_counts = [0] * num_cols
    value_counts = [{} for _ in range(num_cols)]
    max_values = [float('-inf')] * num_cols
    min_values = [float('inf')] * num_cols

    for row in sql_result:
        for idx, col in enumerate(row):
            # Count None values
            if col is None or col == 0 or col == 0.0:
                none_counts[idx] += 1
            # Count value occurrences for diversity check
            value_counts[idx][col] = value_counts[idx].get(col, 0) + 1
    # Calculate scores for each aspect
    none_score = 1 - sum(none_counts) / (num_rows * num_cols)
    print("none_score:", none_score)
    diversity_score = sum(len(values.keys()) / num_rows for values in value_counts) / num_cols
    print("diversity_score:", diversity_score)
    # Combine scores (you might want to adjust weights)
    combined_score = (none_score + diversity_score) / 2
    return combined_score


# TODO
def fd_quality(sql_query, column_mappings, **kwargs):
    data_1 = []
    data_2 = []
    select_columns, target_columns = extract_table_schemas(sql_query, kwargs['source_name'], kwargs['target_name'])
    # Extract the relevant columns from the source based on column mappings
    relevant_source_columns = [src for src, tgt in column_mappings if src in select_columns]
    if len(relevant_source_columns) > 2:
        column_names_1 = list(select_columns.keys())
        column_names_2 = list(target_columns.keys())
        with open(kwargs['test_0_path'], 'r', encoding="utf-8") as file:
            reader = csv.reader(file)
            header = next(reader)
            for row in reader:
                data_1.append(tuple(row))

        data_1_df = pd.DataFrame(data_1, columns=column_names_1)
        with open(kwargs['result_path'], 'r', encoding="utf-8") as file:
            reader = csv.reader(file)
            header = next(reader)
            for row in reader:
                data_2.append(tuple(row))
        # Filter df_1 to include only the relevant columns
        df_1 = data_1_df[relevant_source_columns]
        df_2 = pd.DataFrame(data_2, columns=column_names_2)
        # Use FDTool
        functional_dependencies_1 = analyze_functional_dependencies(df_1)
        # Map source FDs to target FDs
        mapped_fds = map_source_fds_to_target_fds(functional_dependencies_1, column_mappings)
        print("mapped_fds", mapped_fds)
        functional_dependencies_2 = analyze_functional_dependencies(df_2)
        # Compare mapped FDs with target FDs
        fd_comparison, fd_score = compare_fds(mapped_fds, functional_dependencies_2)
        print("fd_score:", fd_score)
        print("fd_comparison:", fd_comparison)
        return fd_score, fd_comparison
    else:
        return 0, None


def analyze_functional_dependencies(df):
    # Initial setup based on FDTool logic
    U = list(df.head(0))
    print("U:", U)
    C = [[[item] for item in U]]
    print("C:", C)
    Closure = {binaryRepr.toBin(Subset, U): set(Subset) for Subset in Apriori_Gen.powerset(U)}
    print("Closure:", Closure)
    Cardinality = {element: None for element in Closure}
    print("Cardinality:", Cardinality)
    # Get functional dependencies
    Closure, F, Cardinality = GetFDs.f(C[0], df, Closure, U, Cardinality)

    print("F:", F)
    # Filter functional dependencies
    filtered_F = []
    for fd in F:
        key, value = fd
        # Check if key columns are of float type
        if not isinstance(df[key[0]].iloc[0], Decimal):
            filtered_F.append(fd)

    print("filtered_F:", filtered_F)
    return filtered_F


def map_source_fds_to_target_fds(source_fds, column_mappings):
    mapped_fds = []
    for fd in source_fds:
        lhs, rhs = fd
        lhs_mapped = [map_column(col, column_mappings) for col in lhs]
        rhs_mapped = map_column(rhs, column_mappings)
        mapped_fds.append((lhs_mapped, rhs_mapped))
    return mapped_fds


def map_column(column, column_mappings):
    for source_col, target_col in column_mappings:
        if source_col == column:
            return target_col
    return column  # Return original column if no mapping found


def compare_fds(mapped_fds, target_fds):
    matches = 0
    fd_comparison = []

    # Convert the FDs to a comparable format
    target_fds_set = set([tuple(fd) for fd in target_fds])

    for mapped_fd in mapped_fds:
        # Construct the FD format for comparison
        comparable_fd = (tuple(mapped_fd[0]), mapped_fd[1])

        # Check if the comparable_fd is present in the target_fds
        if comparable_fd in target_fds_set:
            matches += 1
            fd_comparison.append((mapped_fd, True))
        else:
            fd_comparison.append((mapped_fd, False))

    fd_score = matches / len(mapped_fds) if mapped_fds else 0
    return fd_comparison, fd_score


def reverse_quality(conn, **kwargs):
    # Assuming reverse_format_for_agent and other necessary functions are defined elsewhere
    from agent import Agent
    while True:
        source_examples_str, source_schema_str, target_examples_list, target_schema_list = reverse_format_for_agent(
            kwargs['source_examples'], kwargs['source_schema'], kwargs['target_examples'], kwargs['target_schema']
        )
        reverse_path = kwargs['result_path'].replace('baseline', 'reverse')
        agent_reverse = Agent(kwargs['target_name'], kwargs['source_name'], kwargs['result_path'], target_schema_list,
                              source_schema_str,
                              target_examples_list, source_examples_str, reverse_path, kwargs['token_tracker'],
                              kwargs['logger'],
                              backend=kwargs['backend'],
                              clarify_on=kwargs['clarify_on'], method='monolithic')
        agent_reverse.prompt += "Please don't comment copy queries (both for source and target), as PostgreSQL supports direct file writes from queries."
        print(f"Reverse prompt: {agent_reverse.prompt}")
        gpt_output = agent_reverse.run_baseline()
        print(f"Reverse code: {gpt_output}")
        sql_result = execute_sql(conn, gpt_output)
        if not sql_result:
            print("The SQL result is empty. Skipping to the next iteration.")
            continue
        if "Error:" in sql_result:
            print("Reverse failed")
            return 0
        sql_ini = []
        sql_result_reverse = []
        # Validate the ChatGPT generated SQL script
        # TODO
        with open(kwargs['test_0_path'], 'r', encoding="utf-8") as file:
            reader = csv.reader(file)
            header = next(reader)  # Assuming header is used elsewhere or this is for skipping the header
            for row in reader:
                sql_ini.append(tuple(row))
        sql_ini_df = pd.DataFrame(sql_ini, columns=header)  # Assuming you want to use the header for column names
        reverse_path = reverse_path + f"{kwargs['source_name']}_result_baseline.csv"
        if os.path.exists(reverse_path):
            with open(reverse_path, 'r', encoding="utf-8") as file:
                reader = csv.reader(file)
                header = next(reader)  # For column names in DataFrame
                for row in reader:
                    sql_result_reverse.append(tuple(row))
            sql_result_reverse_df = pd.DataFrame(sql_result_reverse, columns=header)
        else:
            print(f"File not found: {reverse_path}. Skipping to the next iteration.")
            continue

        case_accuracy, is_correct, similarity_scores, validation_error = compare_lists_matching(sql_result_reverse_df,
                                                                                                sql_ini_df)
        print(f"validation_error: {validation_error}")
        print(is_correct)
        print(f"reverse_score: {case_accuracy}")
        return case_accuracy


def reverse_format_for_agent(source_examples, source_schema, target_examples, target_schema):
    # Convert source examples from list to string format
    source_examples_str = json.dumps(source_examples)  # Assuming source_examples is already a list

    # Convert source schema from list to string format
    source_schema_str = json.dumps(source_schema)  # Assuming source_schema is already a list

    # Convert target examples from string to list format
    target_examples_list = ast.literal_eval(target_examples)

    # Convert target schema from string to list format
    target_schema_list = ast.literal_eval(target_schema)

    return source_examples_str, source_schema_str, target_examples_list, target_schema_list
