import pandas as pd
import os
import sys
import numpy as np
import re
import math
import itertools
import Levenshtein
import collections
import random
from pandas.util import hash_pandas_object
from functools import reduce

# from similarity.levenshtein import Levenshtein
import random


def get_shape_regex(word):
    result = []
    try:
        for c in word:
            if c.isupper():
                result.append("X")
            elif c.islower():
                result.append("x")
            elif c in "0123456789":
                result.append("d")
            else:
                result.append(c)
        x1 = re.sub(r"x+", "x*", "".join(result))
        return re.sub(r"X+", "X*", x1)
    except:
        return "nan"


def get_shape(word):
    result = []
    try:
        for c in word:
            if c.isupper():
                result.append("X")
            elif c.islower():
                result.append("x")
            elif c in "0123456789":
                result.append("d")
            else:
                result.append(c)
        return "".join(result)
    except:
        return "nan"


def isna(x):
    return math.isnan(x)


def clean_nan(v):
    if isna(v):
        return 0
    # if v > float('inf')/2.0:
    #    return float('inf')/2.0
    # if v < float('-inf') / 2.0:
    #    return float('-inf') / 2.0
    return v


def get_arithmetic_mean(v1, v2):
    return (v1 + v2) / 2.0


def get_geometric_mean(v1, v2):
    return math.sqrt(v1 * v2)


# compute value ranges
def compute_range_overlap(min_1, max_1, min_2, max_2):
    try:
        overlap = (min(max_1, max_2) - max(min_1, min_2)) / (
            max(max_1, max_2) - min(min_1, min_2)
        )
    except:
        return 0
    if overlap < 0:
        return 0
    return overlap


def de_duplicate_columns(df):
    print("de duplicate")
    if len(df) > 20000:
        table = df[df.sample(20000).transpose().drop_duplicates().index]
    else:
        table = df[df.transpose().drop_duplicates().index]
    print("finish de duplicate")
    return table


def compare_series(s1, s2):
    u1 = s1.dropna()
    u2 = s2.dropna()
    if len(u1) != len(u2):
        return False
    n1 = u1.to_numpy()
    n2 = u2.to_numpy()
    f1 = []
    nf1 = []
    f2 = []
    nf2 = []
    for v in n1:
        vtype = str(type(v))
        if "float" in vtype or "in" in vtype:
            f1.append(v)
        else:
            nf1.append(v)

    for v in n2:
        vtype = str(type(v))
        if "float" in vtype or "in" in vtype:
            f2.append(v)
        else:
            nf2.append(v)
    # f1 = [v for v in n1 if type(v) in [float,int]] #u1[u1.apply(lambda x: type(x) in [float,int])]
    # nf1 = [id(v) for v in n1 if type(v) not in [float,int]] #u1[u1.apply(lambda x: type(x) not in [float,int])]
    # f2 = [v for v in n2 if type(v) in [float,int]]
    # nf2 = [id(v) for v in n2 if type(v) not in [float,int]]
    if len(f1) != len(f2):
        return False
    else:
        f1 = sorted(f1)
        f2 = sorted(f2)
        for index in range(len(f1)):
            i1 = f1[index]
            i2 = f2[index]
            if abs(i2 - i1) != 0 and abs(i2 - i1) / max(abs(i2), abs(i1)) > 0.1:
                return False
        float_r = True
        if len(nf1) > 0:
            if collections.Counter(nf1) == collections.Counter(nf2):
                if float_r:
                    return True
        else:
            return True
    return False


# df1 is the dataframe generated by our algorithms, df2 is the original output schema in the pipelines
def compare_tables(df_generate, df_target):
    # compare length firstly
    if len(df_generate) != len(df_target):
        print("THEY ARE OF DIFFERNET LENGTH: ", len(df_generate), len(df_target))
        return False, []
    else:
        print("THEY ARE OF SAME LENGTH: ", len(df_generate), len(df_target))
    col_map = {}
    map_num = 1
    one_map = {}
    mul_map = {}
    results = []
    # df_generate = de_duplicate_columns(df_generate)
    # df_target = de_duplicate_columns(df_target)
    for col_target in df_target.columns:
        col_map[col_target] = []
        col_target_data = df_target[col_target]
        for col_generate in df_generate.columns:
            col_generate_data = df_generate[col_generate]
            # compare the data
            if compare_series(col_target_data, col_generate_data):
                col_map[col_target].append(col_generate)
                results.append(col_generate)
                break
        # can't find correspond columns, return False
        if len(col_map[col_target]) == 0:
            print("didn't find corresponding columns for {}".format(col_target))
            # df_generate.to_csv("gen.csv")
            # df_target.to_csv("tar.csv")
            # exit()
            return False, []
        map_num = map_num * len(col_map[col_target])
        # split them to two maps, one contain columns which only has one mapped column, mul contains columsn which has multiple mapped columns
        if len(col_map[col_target]) == 1:
            one_map[col_target] = col_map[col_target]
        else:
            mul_map[col_target] = col_map[col_target]
    print("map_num = {}".format(map_num), "MATCHED")
    if map_num >= 1:
        return True, results
    basic_target = pd.DataFrame()
    basic_generate = pd.DataFrame()
    for col_target, col_maps in one_map.items():
        col_map = col_maps[0]
        basic_target[col_target] = df_target[col_target]
        basic_generate[col_target] = df_generate[col_map]
        results.append(col_map)
    if map_num == 1:
        try:
            if [
                s
                for s in (basic_generate == df_generate).sum()
                if s == len(basic_generate)
            ] == len(basic_generate.columns):
                return True, results
        except:
            pass
    # first compare the columns with only 1 map and greedy add the one with multiple choices
    if not compare_dfs(basic_target, basic_generate):
        # basic is different, return false
        return False, []
    for col_target, col_maps in mul_map.items():
        for col_map in col_maps:
            basic_target[col_target] = df_target[col_target]
            basic_generate[col_target] = df_generate[col_map]
            if compare_dfs(basic_target, basic_generate):
                results.append(col_map)
                continue
            else:
                # this column doesn't match, drop it and test another one
                basic_target.drop(col_target, axis=1)
                basic_generate.drop(col_target, axis=1)
        # if none of the candidates in the mapped columns work, return False
        if col_target not in basic_target.columns:
            return False, []
    return True, results


def compare_dfs(df1, df2):
    result1 = get_hash_of_table(df1)
    result2 = get_hash_of_table(df2)
    return collections.Counter(result1) == collections.Counter(result2)


def get_hash_of_table(df):
    arr = df.to_numpy()
    arr = [id(v) for v in arr]
    return arr
    r = []
    for i in range(len(df)):
        r.append(
            reduce(
                lambda x, y: (x + 0x9E3779B97F4A7C17 + (y << 6) + (y >> 2)) ^ y,
                hash_pandas_object(df.iloc[i]),
            )
        )
    # print(r)
    return r


class TableSummary(object):
    def __init__(self, table, filename, data_index):
        self.cols = []  # list of ColumnSummary
        self.schema = [
            str(col).replace("\n", " ").strip() for col in table.columns
        ]  # list of column names
        self.filename = filename
        self.data_index = data_index

    def schema_eq(self, other):
        return len(self.schema) == len(other.schema) and all(
            [self.schema[i] == other.schema[i] for i in range(len(self.schema))]
        )

    def __str__(self):
        # return 'Table {} '.format('\n'.join([str(col) for col in self.cols]))
        return "Table {} ".format(",".join([str(col) for col in self.schema]))

    def get_na_score(self):
        sz = self.cols[0].sz
        _nas = []
        for col in self.cols:
            _nas.append(col.N_nans)
        nas = pd.Series(_nas)
        return (nas.mean(), nas.mean() / float(sz))


class TablePairSummary(object):
    def __init__(self, table1, table2, is_candidate=False):
        self.table1 = table1  # TableSummary
        self.table2 = table2  # TableSummary
        self.col_pairs = []  # list of ColumnPairSummary
        self.is_candidate = is_candidate

    def get_concat_score(self):  # return pair (axis=0, axis=1)
        a0 = self.table1.schema_eq(self.table2)
        a1 = self.table1.cols[0].sz == self.table2.cols[0].sz
        return (int(a0), int(a1))

    def __str__(self):
        # return 'Table Pair: Table 1 = {};\nTable2 = {}\npairs={}'.format(self.table1, self.table2, ''.join(['  {}\n'.format(colp) for colp in self.col_pairs]))
        return "Table Pair: Table 1 = {};\nTable2 = {}\n".format(
            self.table1, self.table2
        )


def get_model():
    from gensim.test.utils import common_texts, get_tmpfile
    from gensim.models import Word2Vec
    import gensim
    import gensim.utils
    from gensim.utils import simple_preprocess
    import re

    model = gensim.models.KeyedVectors.load_word2vec_format(
        "./GoogleNews-vectors-negative300.bin.gz", binary=True
    )
    return model


def tokenize(sentence):
    return re.split(" |_|-|.|,", sentence)


def tidy_sentence(sentence, vocabulary):
    return [word for word in tokenize(sentence) if word in vocabulary]


def compute_sentence_similarity(sentence_1, sentence_2, model_wv):
    vocabulary = model_wv.vocab
    tokens_1 = tidy_sentence(sentence_1, vocabulary)
    tokens_2 = tidy_sentence(sentence_2, vocabulary)
    if len(tokens_1) == 0 or len(tokens_2) == 0:
        return 0
    return model_wv.n_similarity(tokens_1, tokens_2)


def get_features_for_compatibility(table, model, sample=False):
    features = []
    y = []
    cnt = 0
    pairs = []
    _table = table
    if sample and len(table) > 600:
        print("large table: {}".format(len(table)))
        _table = [col for col in table]
        random.shuffle(_table)
        _table = _table[:200]
    for xx in itertools.combinations(_table, 2):
        col1, col2 = xx
        pairs.append((col1, col2))

    if sample:
        random.shuffle(pairs)
        _pairs = []
        pos_cnt = 0
        neg_cnt = 0
        for p in pairs:
            if p[0].is_value and p[1].is_value:
                if pos_cnt < 100:
                    _pairs.append(p)
                pos_cnt += 1
            elif int(p[0].is_value) + int(p[1].is_value) == 1:
                if neg_cnt < 100:
                    _pairs.append(p)
                neg_cnt += 1
        pairs = _pairs

    for col1, col2 in pairs:
        col1.col_name = str(col1.col_name)
        col2.col_name = str(col2.col_name)
        col1_shape = get_shape(col1.col_name)
        col2_shape = get_shape(col2.col_name)
        f1 = Levenshtein.distance(col1.col_name, col2.col_name)
        f2 = float(f1) / float(max(len(col1.col_name), len(col2.col_name)))
        f3 = Levenshtein.distance(col1_shape, col2_shape)
        f4 = float(f3) / float(max(len(col1_shape), len(col2_shape)))
        f5 = abs(len(col1.col_name) - len(col2.col_name))
        f6 = (
            0
            if abs(col1.dtype_to_int(col1.dtype) - col2.dtype_to_int(col2.dtype)) == 0
            else 1
        )
        col1_type_onehot = col1.type_onehot()
        col2_type_onehot = col2.type_onehot()
        # print(col1_type_onehot)
        # print(col2_type_onehot)
        # skip f7 for now
        # f7 = abs(col1.mean - col2.mean)
        f8 = (
            float(abs(col1.nuniques - col2.nuniques))
            / float(max(col1.nuniques, col2.nuniques))
            if max(col1.nuniques, col2.nuniques) > 0
            else 0
        )
        # c1 = col1.astype(str).apply(lambda x: len(x)).mean()
        # c2 = col2.astype(str).apply(lambda x: len(x)).mean()
        # f9 = abs(c1-c2)
        f9 = (
            float(abs(col1.strv_len_mean - col2.strv_len_mean))
            / float(max(col1.strv_len_mean, col2.strv_len_mean))
            if max(col1.strv_len_mean, col2.strv_len_mean) > 0
            else 0
        )
        if col1.dtype == col2.dtype:
            if col1.dtype == "object" or col1.dtype == "str":
                if isinstance(col1.unique_values, pd.Series) and isinstance(
                    col2.unique_values, pd.Series
                ):
                    left_temp = col1.unique_values.isin(col2.unique_values)
                    left_ratio = left_temp.sum()
                    right_temp = col2.unique_values.isin(col1.unique_values)
                    right_ratio = right_temp.sum()
                    f10 = float(left_ratio) / float(col1.sz) + float(
                        right_ratio
                    ) / float(col2.sz)
                else:
                    f10 = 0
            elif col1.dtype in ["int", "float", "float-int", "datetime"]:
                overlapr = (
                    max(col1.value_range[0], col2.value_range[0]),
                    min(col1.value_range[1], col2.value_range[1]),
                )
                if col1.dtype == "datetime":
                    vrange1 = (col1.value_range[1] - col1.value_range[0]).days
                    vrange2 = (col2.value_range[1] - col2.value_range[0]).days
                    overlap = max((overlapr[1] - overlapr[0]).days, 0.0)
                else:
                    vrange1 = col1.value_range[1] - col1.value_range[0]
                    vrange2 = col2.value_range[1] - col2.value_range[0]
                    overlap = max((overlapr[1] - overlapr[0]), 0.0)
                f10_1 = float(overlap) / float(vrange1) if vrange1 > 0 else 0
                f10_2 = float(overlap) / float(vrange2) if vrange2 > 0 else 0
                f10 = f10_1 + f10_2
            else:
                f10 = 0
        else:
            f10 = 0

        f11 = compute_sentence_similarity(col1.col_name, col2.col_name, model)
        # r = [clean_nan(x) for x in [f1, f2, f3, f4, f5, f6, f7, f8, f9, f10]]
        # modified
        r = [
            clean_nan(x)
            for x in [
                col1.nuniques,
                col2.nuniques,
                len(col1.col_name),
                len(col2.col_name),
                col1.strv_len_mean,
                col2.strv_len_mean,
                f1,
                f2,
                f3,
                f4,
                f5,
                f6,
                f8,
                f9,
                f10,
                f11,
            ]
        ]
        # if not np.isfinite(sum(r)):
        #    print('feature vector is not finite: should not happen: ' + ''.join(str(x) for x in r))
        # r[6] = 10000.0
        #    r[-1] = 0
        # print("{} x {}: feature = {} / {}".format(col1.col_name, col2.col_name, r, col1.is_value and col2.is_value))
        col_type_diff_onehot = []
        for idx in range(len(col1_type_onehot)):
            col_type_diff_onehot.append(
                abs(col1_type_onehot[idx] - col2_type_onehot[idx])
            )
        r += col_type_diff_onehot
        # r += col1_type_onehot
        # r += col2_type_onehot
        features.append(r)

        # print(features)
        # add features: for col_name_1 and col_name_2, how often are they melted in training set?

        y.append(int(col1.is_value and col2.is_value))
    return features, y, pairs


def sample(table, length):
    # print(len(table))
    t1 = table
    if len(table) > length:
        t1 = table.sample(length)
    return t1


def get_edit_distance(value_i, value_j):
    edit_distance = (
        Levenshtein.distance(value_i, value_j) * 1.0 / (len(value_i) + len(value_j))
    )
    return edit_distance


def get_column_pair_pattern_value(col1, col2, col1_data, col2_data):
    # they are string values
    result = 0
    col_len_threshold = 10
    if not check_numerical(col1_data) and not check_numerical(col2_data):
        # TBD: sample
        # get the pattern. [A-Z] => A, [a-z] => a
        drop_nan_col1 = col1_data.dropna()
        drop_nan_col2 = col2_data.dropna()
        if (
            len(drop_nan_col1) > col_len_threshold
            and len(drop_nan_col2) > col_len_threshold
        ):
            avg_ratio = 1
            if max(col1.strv_len_mean, col2.strv_len_mean) > 0:
                avg_ratio = float(abs(col1.strv_len_mean - col2.strv_len_mean)) / float(
                    max(col1.strv_len_mean, col2.strv_len_mean)
                )
            # print("avg_ratio {}".format(avg_ratio))
            # print(col1.col_name, col2.col_name, "length ratio:", avg_ratio)
            if avg_ratio < 0.5:
                if col1.shapes is None:
                    col1.shapes = drop_nan_col1.apply(
                        lambda x: get_shape_regex(str(x))
                    ).unique()
                if col2.shapes is None:
                    col2.shapes = drop_nan_col2.apply(
                        lambda x: get_shape_regex(str(x))
                    ).unique()
                pattern1 = col1.shapes
                pattern2 = col2.shapes
                # sample the pattern
                if len(pattern1) > 100:
                    pattern1 = random.sample(list(pattern1), 100)
                if len(pattern2) > 100:
                    pattern2 = random.sample(list(pattern2), 100)
                # print("after de-duplicate {} {} {} {}".format(len(pattern1), len(pattern2), pattern1.iloc[0], pattern2.iloc[0]))
                distance_map1 = {}
                distance_map2 = {}
                for i in range(len(pattern1)):
                    for j in range(len(pattern2)):
                        value_i = pattern1[i]
                        value_j = pattern2[j]
                        edit_distance = get_edit_distance(value_i, value_j)
                        key1 = "{}_{}".format(i, j)
                        key2 = "{}_{}".format(j, i)
                        if key1 in distance_map1:
                            distance_map1[key1].append(edit_distance)
                        else:
                            distance_map1[key1] = [edit_distance]

                        if key2 in distance_map2:
                            distance_map2[key2].append(edit_distance)
                        else:
                            distance_map2[key2] = [edit_distance]
                result = 0
                r_l = []
                r_r = []
                for key, value in distance_map1.items():
                    min_distance = min(value)
                    r_l.append(min_distance)
                for key, value in distance_map2.items():
                    min_distance = min(value)
                    r_r.append(min_distance)
                if len(r_l) > 2:
                    result = sorted(r_l, key=lambda x: x)[: int(len(r_l) / 2)]
                else:
                    result = r_l
                if len(r_r) > 2:
                    result += sorted(r_r, key=lambda x: x)[: int(len(r_r) / 2)]
                else:
                    result += r_r
                if len(result) > 0:
                    result = 1 - sum(result) / len(result)
                else:
                    result = 0
    # print("result is : {}".format(result))
    return result


def check_numerical(col):
    if str(col.dtype) == "object":
        try:
            new_col = col.apply(lambda x: float(str(x).replace(",", "")))
            return True
        except:
            return False
    return True


def find_groupby_key(df):
    cols = []
    df = sample(df, 20000)
    for col in df.columns:
        cols.append(col)
        # return the first cols that are unique
        if len(df[cols]) == len(df[cols].drop_duplicates()):
            if len(cols) != len(df.columns):
                return cols
    return []


def check_group_by(df):
    cols = []
    for c in df.columns:
        # print("TYPE", str(df[c].dtype))
        if str(df[c].dtype).startswith("int") or str(df[c].dtype).startswith("float"):
            break
        else:
            cols.append(c)
    if len(cols) == len(df.columns):
        cols = []
    if len(cols) > 0 and len(df[cols]) != len(df[cols].drop_duplicates()):
        cols = []
    # print("COLS :", cols)
    return cols


class ColumnSummary(object):
    def __init__(
        self,
        col_name,
        col,
        col_pos,
        filename,
        data_index,
        n_cols,
        is_id,
        is_value,
        nan_count=None,
    ):
        self.col_name = col_name
        self.filename = filename
        self.data_index = data_index
        self.col_pos = col_pos
        self.n_cols = n_cols
        self.nuniques = ""
        self.dtype = ""
        self.sz = ""
        self.is_monotonic = False
        self.value_range = None  # pair, for int/float/datetime
        self.shapes = None  # for string
        self.std = None
        self.hasna = False
        if nan_count is not None:
            self.countna = nan_count
        self.countna = 0
        self.mean = 0
        self.most_frequent_vcount = 0
        self.strv_len_mean = 0
        self.unique_values = []
        self.sample = None
        self.set(col)
        self.is_id = is_id
        self.is_value = is_value
        self.N_nans = 0
        self.avg_length = None

    def __str__(self):
        return "col {} ({}): sz = {}, nuniques = {}, dtype = {}, is_monotonic = {}, most_frequent_vcount = {}, hasna = {}, std = {}, value_range = {}, shapes = {}".format(
            self.col_name,
            "na",
            self.sz,
            self.nuniques,
            self.dtype,
            self.is_monotonic,
            self.most_frequent_vcount,
            self.hasna,
            self.std,
            self.value_range if self.value_range is not None else "NA",
            (
                (self.shapes if self.shapes.shape[0] < 10 else "too-many-shapes")
                if self.shapes is not None
                else "NA"
            ),
        )

    def get_col_type(self, dtype, sample):
        if dtype.startswith("int"):
            return "int"
        if dtype.startswith("float"):
            if all([float(int(x)) == x if not isna(x) else True for x in sample]):
                return "float-int"
            else:
                return "float"
        if dtype == "object":
            return "str"
        if dtype.startswith("bool"):
            return "bool"
        if dtype == "datetime64[ns]":
            return "datetime"
        return dtype

    def dtype_to_int(self, dtype):
        # if dtype == 'float':
        #    return 1
        # elif dtype == 'float-int':
        #    return 2
        # elif dtype == 'int':
        #    return 3
        if dtype == "int" or dtype == "float-int":
            return 1
        elif dtype == "float":
            return 2
        elif dtype == "datetime":
            return 4
        elif dtype == "bool":
            return 5
        elif dtype == "object":
            return 6
        else:
            return 7

    def type_onehot(self):
        r = self.dtype_to_int(self.dtype)
        # is int / bool / string / datetime / float
        return [
            int(r == 1),
            int(r == 2),
            int(r == 4),
            int(r == 5),
            int(r == 6),
            int(r == 7),
        ]

    def set(self, col):
        self.sz = col.shape[0]
        if self.sz > 100:
            sample = col.sample(n=20, replace=False, random_state=1)
        else:
            sample = col[:20]
        if self.countna is None:
            self.countna = col.isna().sum()
        self.hasna = self.countna > 0
        self.is_monotonic = col.is_monotonic
        self.dtype = self.get_col_type(str(col.dtype), sample)
        # self.most_frequent_vcount = col.value_counts().max()
        str_length = col.astype(str).str.len()
        self.strv_len_mean = str_length.mean()
        self.strv_len_std = str_length.std()
        self.unique_hash = collections.Counter(col)  # {k:1 for k in col_unique}
        if len(self.unique_hash) > 0:
            self.most_frequent_vcount = self.unique_hash.most_common()[0][1]
        else:
            # print('ZERO unique_hash ', col)
            self.most_frequent_vcount = 0

        col_unique = list(self.unique_hash.keys())
        self.nuniques = len(col_unique)
        self.unique_values = pd.Series(col_unique)
        if self.dtype in ["int", "float", "float-int", "datetime"]:
            self.value_range = (col.min(), col.max())
            if self.dtype != "datetime":
                self.std = col.std()
                self.mean = col.mean()
        # elif self.dtype in ["str"]:
        #     # temp = col.apply(lambda x: len(str(x)))
        #     #value_range = (temp.min(), temp.max())
        #     if self.nuniques < 1000:
        #         self.unique_values = pd.Series(col.unique())#col.drop_duplicates()
        #     # get shape
        #     # print('col = {} {}, shapes = {}'.format(col.dtype, col, col.apply(lambda x: get_shape(x))))
        #     # self.shapes = col.apply(lambda x: get_shape_regex(str(x))).unique()

    def get_groupby_features(self, col_name_groupby_counter, col_name_value_counter):
        f1 = self.nuniques
        if self.sz > 0:
            f2 = float(self.nuniques) / float(self.sz)
        else:
            f2 = 0
        f3 = self.is_monotonic
        f4 = self.type_onehot()
        f4 = f4[:-1]
        col_name = str(self.col_name)
        f5 = 0
        f6 = 0
        f7 = 0
        f8 = 0
        vrange = 0
        # f9 = [False for i in range(len(shape_vec))]
        if self.dtype in ["int", "float", "float-int", "datetime"]:
            if self.dtype == "datetime":
                vrange = (self.value_range[1] - self.value_range[0]).days
                if isna(vrange):
                    vrange = 0
                f5 = (
                    (float(self.nuniques) / float(vrange))
                    if (vrange > 0 and not isna(vrange))
                    else 0
                )  # range
            else:
                vrange = self.value_range[1] - self.value_range[0]
                if isna(vrange):
                    vrange = 0
                f5 = (
                    (float(self.nuniques) / float(vrange))
                    if (vrange > 0 and not isna(vrange))
                    else 0
                )  # range
                f6 = self.std
                f7 = (
                    (float(self.mean - self.value_range[0]) / float(vrange))
                    if (vrange > 0 and not isna(vrange))
                    else 0
                )
                # f6 = # weather it is year
                # f7 = # weather it is month
        # elif self.dtype in ['str']:
        #    f8 = len(self.shapes)# Nshapes
        # f9 = [any([s_==s for s_ in self.shapes]) for s in shape_vec]

        # relative col position in a table: note self.total_cols_in_table should not be 0
        relative_col_pos = float(self.col_pos) / float(self.n_cols)

        # count how many times this col has been used as groupby vs. vals in other tables (except this one table)
        col_name_used_as_groupby = col_name_groupby_counter[self.col_name]
        col_name_used_as_val = col_name_value_counter[self.col_name]

        # if(self.is_grouped == True):
        #    col_name_used_as_groupby -= 1
        # if(self.is_value == True):
        #    col_name_used_as_val -= 1

        # assert col_name_used_as_groupby >= 0, "col_cnt cannot be less than 0"
        # assert col_name_used_as_val >= 0, "col_cnt cannot be less than 0"

        gb_vs_val = (
            (float(col_name_used_as_groupby) / float(col_name_used_as_val))
            if col_name_used_as_val != 0
            else col_name_used_as_groupby
        )

        features = f4
        features += [
            f1,
            f2,
            self.sz,
            self.col_pos,
            relative_col_pos,
            f3,
            f5,
            f7,
        ]  # , vrange]
        features += [col_name_used_as_groupby, col_name_used_as_val, gb_vs_val]
        f10 = self.countna > 0
        f11 = self.most_frequent_vcount
        f12 = float((self.most_frequent_vcount)) / float(self.sz)
        features += [f10, f11, f12]
        r = [clean_nan(x) for x in features]
        if not np.isfinite(sum(r)):
            r[4] = 0.0
            r[5] = 0.0
        assert np.isfinite(sum(r))
        return r


class ColumnPairSummary(object):
    def __init__(
        self,
        col_l,
        col_r,
        col_l_data,
        col_r_data,
        left_ratio=0,
        right_ratio=0,
        unique_overlap=0,
    ):
        self.col_l = col_l
        self.col_r = col_r

        if col_r_data is None and col_l_data is None:
            self.left_ratio = left_ratio
            self.right_ratio = right_ratio
            self.unique_overlap = unique_overlap
        else:
            col_l_unique = (
                col_l.unique_values
            )  # col_l_data.unique() #.drop_duplicates()
            col_r_unique = (
                col_r.unique_values
            )  # col_r_data.unique() #.drop_duplicates()
            self.col_l_unique = col_l_unique
            self.col_r_unique = col_r_unique
            left_temp = [col_l.unique_hash[k] for k in self.col_r.unique_hash]
            self.left_ratio = sum(left_temp)
            self.right_ratio = sum(
                [col_r.unique_hash[k] for k in self.col_l.unique_hash]
            )
            self.unique_overlap = len([v for v in left_temp if v > 0])
            self.union_size = (
                len(col_l_unique) + len(col_r_unique) - self.unique_overlap
            )
            if col_l.dtype not in ["int", "float", "float-int"]:
                if self.union_size == 0:
                    self.jaccard_value = 0
                else:
                    self.jaccard_value = self.unique_overlap / self.union_size
            else:
                self.jaccard_value = 0
            self.range_overlap = 0
            self.pattern_value = 0
            self.col_name_score = 1 - get_edit_distance(
                self.col_l.col_name, self.col_r.col_name
            )

            # print("{} {} {} {} {}\n".format(col_l.col_name, col_r.col_name, self.jaccard_value, len(col_l_data), len(col_r_data)))
            # if self.jaccard_value < 0.3:
            #     self.pattern_value = get_column_pair_pattern_value(col_l, col_r, col_l_unique, col_r_unique)

    def set_pattern_value(self):
        self.pattern_value = get_column_pair_pattern_value(
            self.col_l,
            self.col_r,
            pd.Series(self.col_l_unique),
            pd.Series(self.col_r_unique),
        )

    def set_range_overlap(self):
        f7 = 0
        if self.col_l.value_range is not None and self.col_r.value_range is not None:
            try:
                min_1 = self.col_l.value_range[0]
                max_1 = self.col_l.value_range[1]
                min_2 = self.col_r.value_range[0]
                max_2 = self.col_r.value_range[1]
                union = max(max_1, max_2) - min(min_1, min_2)
                # print("union: ", union)
                if union != 0:
                    range_1 = max_1 - min_1
                    range_2 = max_2 - min_2
                    if range_1 == 0:
                        range_1 = 1
                    if range_2 == 0:
                        range_2 = 1
                    f7 = min((range_1) / union, (range_2) / union)
                # it might be nan
                if math.isnan(float(f7)):
                    f7 = 0
            except:
                f7 = 0

        self.range_overlap = f7
        # print(self.col_l.value_range, self.col_r.value_range, self.range_overlap)

    def __str__(self):
        return "ColPair [{}] and [{}]; lratio = {}, rratio = {}, overlap = {}".format(
            self.col_l,
            self.col_r,
            self.left_ratio,
            self.right_ratio,
            self.unique_overlap,
        )

    def get_join_features(self):
        # f1: overlap ratios (this is multi-set containment ratio)
        f1_left = float(self.left_ratio) / float(self.col_l.sz)
        f1_right = float(self.right_ratio) / float(self.col_r.sz)
        # f1 = get_geometric_mean(f1_left, f1_right)
        f1 = max(f1_left, f1_right)

        # f2: data type
        f2 = self.col_l.type_onehot()
        onehot_type = f2

        # f3: monotonic
        f3 = self.col_l.is_monotonic + self.col_r.is_monotonic

        # f4: col_position
        f4_left = self.col_l.col_pos
        f4_right = self.col_r.col_pos
        f4_mean = get_arithmetic_mean(f4_left, f4_right)
        f4_min = min(f4_left, f4_right)

        # f4: col_pos ratio
        f4_left_ratio = float(self.col_l.col_pos) / float(self.col_l.n_cols)
        f4_right_ratio = float(self.col_r.col_pos) / float(self.col_r.n_cols)
        f4_ratio_mean = get_arithmetic_mean(f4_left_ratio, f4_right_ratio)
        f4_ratio_min = min(f4_left_ratio, f4_right_ratio)

        # f5: ratio of unique values
        f5_left = float(self.col_l.nuniques) / float(self.col_l.sz)
        f5_right = float(self.col_r.nuniques) / float(self.col_r.sz)
        f5 = max(f5_left, f5_right)
        f5_is_unique = f5 == 1

        # f6: ratio of left / right
        f6 = (
            float(self.col_l.sz) / float(self.col_r.sz)
            if self.col_l.sz > self.col_r.sz
            else float(self.col_r.sz) / float(self.col_l.sz)
        )

        # f7: range overlap
        f7 = 0
        f7_left = 0
        f7_right = 0
        if self.col_l.value_range is not None and self.col_r.value_range is not None:
            if self.col_l.dtype == "datetime64[ns]":
                # could not get this to work for dates, so like string us f1
                # f7 = compute_range_overlap(compute_ts(self.col_l.value_range[0]), compute_ts(self.col_l.value_range[1]), compute_ts(self.col_r.value_range[0]), compute_ts(self.col_r.value_range[1]))
                f7 = max(f1_left, f1_right)
            else:
                f7 = compute_range_overlap(
                    self.col_l.value_range[0],
                    self.col_l.value_range[1],
                    self.col_r.value_range[0],
                    self.col_r.value_range[1],
                )
        else:
            f7 = max(f1_left, f1_right)

        # get the row-count ratio, normalize to small-side / large-side
        row_cnt_ratio = min(
            float(self.col_l.sz) / float(self.col_r.sz),
            float(self.col_r.sz) / float(self.col_l.sz),
        )

        orig_features = onehot_type + [
            self.col_l.is_id,
            self.col_r.is_id,
            self.col_l.sz,
            self.col_r.sz,
            row_cnt_ratio,
            f1_left,
            f1_right,
            f1,
            # standardize_type(self.col_l.dtype),
            self.col_l.is_monotonic,
            self.col_r.is_monotonic,
            f4_left,
            f4_right,
            f4_mean,
            f4_min,
            f4_left_ratio,
            f4_right_ratio,
            f4_ratio_mean,
            f4_ratio_min,
            f5_left,
            f5_right,
            f5,
            f5_is_unique,
            f7,
        ]
        return [clean_nan(x) for x in orig_features]
